kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # base64 encoded value of "root"
  MYSQL_USER: cm9vdA== # base64 encoded value of "root"
  MYSQL_DATABASE: ZGV2b3BzZGI= # base64 encoded value of "devopsdb"